### ISSUE TITLE
Duplicate URLs can show under Browsers

### ISSUE THREAD

**Issue by KalebMatthews** [WithOneVisionTechnologies/omnihive-manager-vscode#13]
There is an issue where duplicate URLs can be listed in the browsers list. Image provided.

![Screen Shot 2021-06-01 at 1 58 58 PM](https://user-images.githubusercontent.com/29708600/120369746-b67ce280-c2e1-11eb-8fbf-05bc2579c633.png)

**Comment by doug-shontz** [comment]
This should be fixed in the latest version I'm pushing, but, if it's not, then that means it's actually a problem in how OH is generating the URL's and we'll move it over to there.

**Comment by doug-shontz** [comment]
Confirmed fixed.  Will reopen if necessary.
